version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ishipping_web
    # '/start' is the shell script used to run the service
    command: /app/start.sh
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - redis
      - db

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=ishipping
      - MYSQL_ROOT_PASSWORD=123456

  redis:
    image: redis:latest

  celery_worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ishipping_celery_worker
    command: /app/start-celery-worker.sh
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ishipping_celery_beat
    command: /app/start-celery-beat.sh
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - celery_worker
